Feat/database configuration
MajewskiOliwier/JavaProject pull request #1
Opened 2024-10-22 11:07 UTC by MajewskiOliwier

I added basic DB config and java classes using java JPA. I also used Lombok for cleaner code. Should be good.

2024-10-22 11:50 UTC, TomaszMarek commented
Check again which fields require a validation

2024-10-24 15:18 UTC, TomaszMarek requested changes

2024-10-24 15:18 UTC, TomaszMarek commented on src/main/java/com/example/JavaProject/entity/User.java
> +    private Integer age;
Maybe limit that age??

2024-10-24 15:18 UTC, TomaszMarek commented on src/main/java/com/example/JavaProject/entity/User.java
> +    private String email;
Where is the email validation?

2024-10-24 16:49 UTC, MajewskiOliwier commented on src/main/java/com/example/JavaProject/entity/User.java
> +    private String email;
done

2024-10-24 16:50 UTC, MajewskiOliwier commented on src/main/java/com/example/JavaProject/entity/User.java
> +    private Integer age;
ok, now the Top limit is 120

2024-10-24 17:01 UTC, TomaszMarek requested changes
Do squash!

2024-10-29 08:28 UTC, TomaszMarek approved these changes

2024-10-29 09:12 UTC, merged